# Generated by Django 3.2.7 on 2021-09-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lat',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='long',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
